name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: sudo ./configure
      
    - name: build
      run: make build

    - name: Upload résumé to download
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: résumé.pdf
        asset_name: résumé
        tag: ${{ github.ref }}
        overwrite: true
        body: "The PDF version of the résumé"