name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: sudo ./configure
      
    - name: build
      run: make build

    - name: Delete old release résumé
      uses: mknejp/delete-release-assets@v1
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        assets: résumé-tanay-prabhudesai.pdf

    - name: Upload résumé to download
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: resume.pdf
        asset_name: résumé-tanay-prabhudesai.pdf
        release_name: résumé
        tag: ${{ github.ref }}
        overwrite: true
        body: "The PDF version of the résumé"