name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: sudo ./configure
      
    - name: build
      run: make build
      
    - uses: actions/upload-artifact@v3
      with:
        name: resume
        path: resume.pdf